### ISSUE TITLE
Update INSTALL.md with correct paths

### ISSUE THREAD

**Issue by rolker** [OceanDataTools/sealog-client-vessel#11]
Paths all reference client-vehicle instead of client-vessel.
I did not notice this while I was cut'n'pasting for my first test installation and ended with a working copy of the vehicle client instead of the one for a vessel.
I did then install the vessel version and have them running together. Of course, I did modify the apache path for one of them.

**Comment by webbpinner** [comment]
Thanks for pointing this out... issue has been corrected.
